repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: |
          (?x)  # Verbose mode
          ^juju/client/schemas-juju-.*[.]json$  |
          ^tests/.*[.]charm$  |
          ^examples/.*[.]charm$
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
        # Overlays deliberately comprise multiple YAML documents per file
        exclude: "^tests/integration/bundle/test-overlays/.*multi.*yaml$"
      - id: check-toml
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: "^juju/client/schemas-juju-.*[.]json$"
      - id: trailing-whitespace
      - id: detect-private-key
        exclude: "^tests/.*$"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [ --preview, --fix ]
      - id: ruff-format
        args: [ --preview ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
      exclude: "^juju/client/schemas-juju-.*[.]json$"

ci:
  autofix_prs: false
