version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - method: pip
      packages:
        - sphinx==5.3.0
        - sphinxcontrib-asyncio
        - sphinx_rtd_theme

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py
